info:
    name: mStore Web UI
    version: 1.0.0

server:
    port: 8080

zuul:
    host:
        socket-timeout-millis: 20000
        connect-timeout-millis: 5000
    routes:
        auth-service:
            path: /api/auth/** #AuthRest
            url: http://localhost:8000/auth/
        cart-service:
            path: /api/carts/carts/** #CartRest
            url: http://localhost:8000/carts/
        catalog-service:
            path: /api/catalog/** #ProductRest, ItemRest
            url: http://localhost:8000/
        customer-service:
            path: /api/customers/** #AddressRest, CustomerRest
            url: http://localhost:8000/
        order-service:
            path: /api/orders/orders/** #OrderRest
            url: http://localhost:8000/orders/
        review-service:
            path: /api/reviews/reviews/** #ReviewRest
            url: http://localhost:8000/reviews/
        login-service: # mock auth
            path: /login
            url: http://localhost:8000/login
        logout-service: # mock auth
            path: /logout
            url: http://localhost:8000/logout
