logging.level:
  .: INFO
  org.springframework: ERROR

server:
  port: 9595

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mstore
    username: mstore
    password: mstore123
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: update